/**
 * Türkçe ülke isimlerinden ISO 3166-1 alpha-2 kodlarına mapping
 */
export function getCountryCode(countryName: string): string {
  const countryCodeMap: Record<string, string> = {
    // Türkçe ülke isimleri
    'Türkiye': 'TR',
    'Amerika Birleşik Devletleri': 'US',
    'Birleşik Krallık': 'GB',
    'Büyük Britanya ve İrlanda Birleşik Krallığı': 'GB',
    'Almanya': 'DE',
    'Fransa': 'FR',
    'İtalya': 'IT',
    'İspanya': 'ES',
    'Rusya': 'RU',
    'Çin Halk Cumhuriyeti': 'CN',
    'Japonya': 'JP',
    'Hindistan': 'IN',
    'Brezilya': 'BR',
    'Kanada': 'CA',
    'Avustralya': 'AU',
    'Arjantin': 'AR',
    'Meksika': 'MX',
    'Güney Kore': 'KR',
    'Endonezya': 'ID',
    'Hollanda': 'NL',
    'İsviçre': 'CH',
    'İsveç': 'SE',
    'Polonya': 'PL',
    'Belçika': 'BE',
    'Avusturya': 'AT',
    'Norveç': 'NO',
    'Danimarka': 'DK',
    'Finlandiya': 'FI',
    'İrlanda': 'IE',
    'Portekiz': 'PT',
    'Yunanistan': 'GR',
    'Çek Cumhuriyeti': 'CZ',
    'Romanya': 'RO',
    'Macaristan': 'HU',
    'Ukrayna': 'UA',
    'Şili': 'CL',
    'Kolombiya': 'CO',
    'Peru': 'PE',
    'Venezuela': 'VE',
    'Küba': 'CU',
    'Mısır': 'EG',
    'Güney Afrika': 'ZA',
    'Kenya': 'KE',
    'Nijerya': 'NG',
    'Cezayir': 'DZ',
    'Fas': 'MA',
    'Tunus': 'TN',
    'İsrail': 'IL',
    'Suudi Arabistan': 'SA',
    'Birleşik Arap Emirlikleri': 'AE',
    'İran': 'IR',
    'Irak': 'IQ',
    'Pakistan': 'PK',
    'Bangladeş': 'BD',
    'Tayland': 'TH',
    'Vietnam': 'VN',
    'Filipinler': 'PH',
    'Malezya': 'MY',
    'Singapur': 'SG',
    'Yeni Zelanda': 'NZ',
    'Jamaika': 'JM',
    'Yeşil Burun Adaları': 'CV',
    'Kıbrıs': 'CY',
    'Britanya Kıbrısı': 'CY',
    
    // Tarihsel ülkeler - en yakın modern bayrak
    'Osmanlı İmparatorluğu': 'TR',
    'Nazi Almanyası': 'DE',
    'Sovyetler Birliği': 'RU',
    'Rusya Sovyet Federatif Sosyalist Cumhuriyeti': 'RU',
    'Avusturya İmparatorluğu': 'AT',
    'İtalyan Sosyal Cumhuriyeti': 'IT',
    'İtalya Krallığı': 'IT',
    'Libya Arap Cumhuriyeti': 'LY',
    'Baas Partisi Irak\'ı': 'IQ',
    'Filistin Devleti': 'PS',
    'Zanzibar Sultanlığı': 'TZ',
    
    // Özel durumlar
    'Bilinmiyor': '',
    'Vatansız': '',
    'Unknown': '',
  };

  return countryCodeMap[countryName] || '';
}
